### ISSUE TITLE
wiki example not direct to correct example

### ISSUE THREAD

**Issue by nongbaoting** [PDBeurope/protvista-pdb#4]
Hi, I am very interested in your wonderful project but I don't know how to use it, because the example codes were missing. would you like to provide those examples again? thanks

**Comment by mandarsd** [comment]
Hi,
There seems to be some issue with the plunkr platform.
I've reported the bug - https://github.com/plnkr/feedback/issues/593
Hope they will fix it soon!

**Comment by nongbaoting** [comment]
Thanks for your reply, from your answer, I realize the plunkr may change their URLs. I checked and found that they have changed your project URL to "https://plnkr.co/edit/nPNvqHhyamzHGrCT?preview".

**Comment by mandarsd** [comment]
Plnkr has fixed the issue. I would suggest you to view the demos in the embed mode instead of the edit mode as it could accidentally modify stuff.
Demo1 - https://embed.plnkr.co/plunk/bMLQL51OrR26lioc
